name: cabal

on:
  push:
    branches: [ci-cabal, wip/thoralf]
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.4"]
        ghc:
          - "8.2.2"
          - "8.8.4"
          - "8.10.7"
          - "9.0.1"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: haskell/actions/setup@v1
      name: Setup GHC and cabal-install
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v2
      name: cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: build
      run: |
        cabal v2-update
        cabal v2-build all:libs
        cabal v2-build ghc-tcplugins-trace:hlint --enable-tests

    - name: test ghc-tcplugins-trace:hlint
      run: cabal v2-test ghc-tcplugins-trace:hlint --test-show-details=direct --test-option="--color=always"
