name: stack

on:
  push:
    branches: [ci-stack, wip/thoralf]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.4"]
        ghc:
          - "8.2.2"
          # Could not find module ‘Language.Haskell.Printf’ with 8.4.4
          # - "8.4.4"
          - "8.6.5"
          - "8.8.4"
          - "8.10.7"
          - "9.0.1"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: haskell/actions/setup@v1
      name: Setup Stack
      with:
        enable-stack: true
        stack-version: 'latest'
        cabal-version: ${{ matrix.cabal }}

    - uses: rwe/actions-hlint-setup@v1
      name: Set up HLint
      with:
        version: "3.3.4"

    - uses: actions/cache@v2
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: build
      run: stack build --stack-yaml=./stack/stack-${{ matrix.ghc }}.yaml

    - uses: rwe/actions-hlint-run@v2
      name: hlint
      with:
        path: '["ghc-tcplugins-trace"]'
        fail-on: suggestion
